#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

npm run prep-svgs
npm run lint
npm run prettier
npm run package
git add --all
